### PR TITLE
fix for missing link in the docker container.

### PR DESCRIPTION
**Pull request by sergeykolychev**
@piiswrong 
please try this, as I think it should fix the perl tests (if there's a password less sudo), though of course this hack is not a correct way to compensate for the lack of the lib in the docker, somebody probably should apply the fix to the docker itself. 
On my  AWS box I have this:
```
ubuntu@ip:~$ dpkg -L libcuda1-375
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libcuda.so.375.66
/usr/lib/i386-linux-gnu
/usr/lib/i386-linux-gnu/libcuda.so.375.66
/usr/share
/usr/share/doc
/usr/share/doc/libcuda1-375
/usr/share/doc/libcuda1-375/changelog.Debian.gz
/usr/share/doc/libcuda1-375/copyright
/usr/lib/x86_64-linux-gnu/libcuda.so.1
/usr/lib/x86_64-linux-gnu/libcuda.so
/usr/lib/i386-linux-gnu/libcuda.so.1
/usr/lib/i386-linux-gnu/libcuda.so
```
Also please see this https://github.com/NVIDIA/nvidia-docker/issues/374

### CODE REVIEW

**Comment by piiswrong** [comment]
This looks too hacky.
@mli any idea what's going on?

**Comment by sergeykolychev** [comment]
@piiswrong @mli AFAIK the nvidia/cuda:7.5-cudnn5-devel docker on which our testing docker is build upon simply does not have file libcuda.so.1
Perl failed because it runs its tests with PERL_DL_NONLAZY=1 and tries to load and resolve every symbol even if they are not used in the actual tests.
The libmxnet.so is not linked against libcuda.so.1 on master branch (perl tests do not fail), this rtc change makes libmxnet.so to be explicitly linked against libcuda.so.1 and the absence of the file in the testing docker container env became apparent.

**Comment by mli** [comment]
i'm not quite sure about this problem. maybe submit this issue to https://github.com/NVIDIA/nvidia-docker ?

**Comment by sergeykolychev** [comment]
@piiswrong this will 'probably' help to get missing libcuda.so.1 onto the CI docker and make perl tests pass.

**Pull request closed without merging**
